services:
  web:
    container_name: shadowverse-tools-api
    image: shadowverse-tools-api-prod:1.0.0
    build:
      context: .
      target: production
      dockerfile: ./Dockerfile
    ports:
      - 1337:1337
      - 9229:9229
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
