services:
    dev:
        container_name: shadowverse-tools-api
        image: shadowverse-tools-api-dev:1.0.0
        build:
            context: .
            target: development
            dockerfile: ./Dockerfile
        ports:
            - 3000:3000
            - 9229:9229
        volumes:
            - .:/app
            - /app/node_modules
        restart: unless-stopped
