version: '3'

services:
  web:
    container_name: shadowverse-tools-api
    image: shadowverse-tools-api-dev:1.0.0
    depends_on:
      - database
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    ports:
      - 1337:1337
      - 9229:9229
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
    networks:
      - shadowverse-tools-network
  database:
    container_name: shadowverse-tools-db
    image: 'postgres:16.3'
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=$DATABASE_PASSWORD
      - POSTGRES_USER=$DATABASE_USER
      - POSTGRES_DB=$DATABASE_DB
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - shadowverse-tools-network

networks:
  shadowverse-tools-network:
    external: false
